// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxslackmessage.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MxSlackMessage module
	public static mxslackmessage.proxies.Message dS_Message(IContext context, mxslackmessage.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxSlackMessage.DS_Message", params);
			return result == null ? null : mxslackmessage.proxies.Message.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Blocks_AddBlock(IContext context, mxslackmessage.proxies.Blocks _blocks)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Blocks", _blocks == null ? null : _blocks.getMendixObject());
			Core.execute(context, "MxSlackMessage.IVK_Blocks_AddBlock", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_TestMessage_SendToSlack(IContext context, mxslackmessage.proxies.TestMessage _testMessage, mxslackmessage.proxies.Message _message)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			params.put("Message", _message == null ? null : _message.getMendixObject());
			Core.execute(context, "MxSlackMessage.IVK_TestMessage_SendToSlack", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Webhook_Save(IContext context, mxslackmessage.proxies.Webhook _webhook)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Webhook", _webhook == null ? null : _webhook.getMendixObject());
			Core.execute(context, "MxSlackMessage.IVK_Webhook_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean message_AddLine(IContext context, mxslackmessage.proxies.Message _message, mxslackmessage.proxies.EnumTextType _textType, java.lang.String _text3000)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Message", _message == null ? null : _message.getMendixObject());
			params.put("TextType", _textType == null ? null : _textType.name());
			params.put("Text3000", _text3000);
			return (java.lang.Boolean)Core.execute(context, "MxSlackMessage.Message_AddLine", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxslackmessage.proxies.Message message_Initialize(IContext context, java.lang.String _notificationText, mxslackmessage.proxies.EnumTextType _textType)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NotificationText", _notificationText);
			params.put("TextType", _textType == null ? null : _textType.name());
			IMendixObject result = (IMendixObject)Core.execute(context, "MxSlackMessage.Message_Initialize", params);
			return result == null ? null : mxslackmessage.proxies.Message.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean message_Send(IContext context, mxslackmessage.proxies.Message _message, java.lang.String _webhookKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Message", _message == null ? null : _message.getMendixObject());
			params.put("WebhookKey", _webhookKey);
			return (java.lang.Boolean)Core.execute(context, "MxSlackMessage.Message_Send", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxslackmessage.proxies.Webhook webhook_Ensure(IContext context, java.lang.String _label, java.lang.String _key, java.lang.String _uRL)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Label", _label);
			params.put("Key", _key);
			params.put("URL", _uRL);
			IMendixObject result = (IMendixObject)Core.execute(context, "MxSlackMessage.Webhook_Ensure", params);
			return result == null ? null : mxslackmessage.proxies.Webhook.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxslackmessage.proxies.Webhook webhook_RetrieveByKey(IContext context, java.lang.String _webhookKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("WebhookKey", _webhookKey);
			IMendixObject result = (IMendixObject)Core.execute(context, "MxSlackMessage.Webhook_RetrieveByKey", params);
			return result == null ? null : mxslackmessage.proxies.Webhook.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean webhook_Validate(IContext context, mxslackmessage.proxies.Webhook _webhook)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Webhook", _webhook == null ? null : _webhook.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MxSlackMessage.Webhook_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}