// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackmessage.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the SlackMessage module
	public static slackmessage.proxies.EnumTextType convert_Mrkdwn_TextType(IContext context, boolean _mrkdwn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Mrkdwn", _mrkdwn);
			java.lang.String result = (java.lang.String)Core.execute(context, "SlackMessage.Convert_Mrkdwn_TextType", params);
			if (result == null)
				return null;
			return slackmessage.proxies.EnumTextType.valueOf(result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean convert_TextType_Mrkdwn(IContext context, slackmessage.proxies.EnumTextType _textType)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TextType", _textType == null ? null : _textType.name());
			return (java.lang.Boolean)Core.execute(context, "SlackMessage.Convert_TextType_Mrkdwn", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static slackmessage.proxies.Message dS_Message(IContext context, slackmessage.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "SlackMessage.DS_Message", params);
			return result == null ? null : slackmessage.proxies.Message.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Blocks_AddBlock(IContext context, slackmessage.proxies.Blocks _blocks)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Blocks", _blocks == null ? null : _blocks.getMendixObject());
			Core.execute(context, "SlackMessage.IVK_Blocks_AddBlock", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_TestMessage_SendToSlack(IContext context, slackmessage.proxies.TestMessage _testMessage, slackmessage.proxies.Message _message)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			params.put("Message", _message == null ? null : _message.getMendixObject());
			Core.execute(context, "SlackMessage.IVK_TestMessage_SendToSlack", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Webhook_Save(IContext context, slackmessage.proxies.Webhook _webhook)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Webhook", _webhook == null ? null : _webhook.getMendixObject());
			Core.execute(context, "SlackMessage.IVK_Webhook_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void message_AddLine(IContext context, slackmessage.proxies.Message _message, slackmessage.proxies.EnumTextType _textType, java.lang.String _text3000)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Message", _message == null ? null : _message.getMendixObject());
			params.put("TextType", _textType == null ? null : _textType.name());
			params.put("Text3000", _text3000);
			Core.execute(context, "SlackMessage.Message_AddLine", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static slackmessage.proxies.Message message_Create(IContext context, java.lang.String _notificationText200, slackmessage.proxies.EnumTextType _textType)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NotificationText200", _notificationText200);
			params.put("TextType", _textType == null ? null : _textType.name());
			IMendixObject result = (IMendixObject)Core.execute(context, "SlackMessage.Message_Create", params);
			return result == null ? null : slackmessage.proxies.Message.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean message_CreateAndSend(IContext context, java.lang.String _notificationText200, slackmessage.proxies.EnumTextType _notificationTextType, java.lang.String _text3000, slackmessage.proxies.EnumTextType _text3000TextType, java.lang.String _webhookKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NotificationText200", _notificationText200);
			params.put("NotificationTextType", _notificationTextType == null ? null : _notificationTextType.name());
			params.put("Text3000", _text3000);
			params.put("Text3000TextType", _text3000TextType == null ? null : _text3000TextType.name());
			params.put("WebhookKey", _webhookKey);
			return (java.lang.Boolean)Core.execute(context, "SlackMessage.Message_CreateAndSend", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean message_Send(IContext context, slackmessage.proxies.Message _message, java.lang.String _webhookKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Message", _message == null ? null : _message.getMendixObject());
			params.put("WebhookKey", _webhookKey);
			return (java.lang.Boolean)Core.execute(context, "SlackMessage.Message_Send", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static slackmessage.proxies.Webhook webhook_Ensure(IContext context, java.lang.String _label, java.lang.String _key, java.lang.String _uRL)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Label", _label);
			params.put("Key", _key);
			params.put("URL", _uRL);
			IMendixObject result = (IMendixObject)Core.execute(context, "SlackMessage.Webhook_Ensure", params);
			return result == null ? null : slackmessage.proxies.Webhook.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static slackmessage.proxies.Webhook webhook_RetrieveByKey(IContext context, java.lang.String _webhookKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("WebhookKey", _webhookKey);
			IMendixObject result = (IMendixObject)Core.execute(context, "SlackMessage.Webhook_RetrieveByKey", params);
			return result == null ? null : slackmessage.proxies.Webhook.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean webhook_Validate(IContext context, slackmessage.proxies.Webhook _webhook)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Webhook", _webhook == null ? null : _webhook.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "SlackMessage.Webhook_Validate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}