// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackmessage.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the SlackMessage module

	/**
	* The number of seconds to wait max for Slack to respond when sending the message.
	*/
	public static java.lang.Long getSlackRequestTimeout()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("SlackMessage.SlackRequestTimeout");
	}
}