// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackmessage.proxies;

public enum Enum_LogNode
{
	SlackMessage(new java.lang.String[][] { new java.lang.String[] { "en_US", "SlackMessage" }, new java.lang.String[] { "nl_NL", "SlackMessage" } }),
	SlackMessageSlash(new java.lang.String[][] { new java.lang.String[] { "en_US", "SlackMessageSlash" } }),
	SlackMessageSend(new java.lang.String[][] { new java.lang.String[] { "en_US", "SlackMessageSend" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_LogNode(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
