// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackmessage.proxies;

public class MessageText
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageTextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SlackMessage.MessageText";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageTextType("MessageTextType"),
		MessageText("MessageText"),
		MessageText_Block("SlackMessage.MessageText_Block");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessageText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SlackMessage.MessageText"));
	}

	protected MessageText(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageTextMendixObject)
	{
		if (messageTextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SlackMessage.MessageText", messageTextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SlackMessage.MessageText");

		this.messageTextMendixObject = messageTextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MessageText.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static slackmessage.proxies.MessageText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return slackmessage.proxies.MessageText.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static slackmessage.proxies.MessageText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new slackmessage.proxies.MessageText(context, mendixObject);
	}

	public static slackmessage.proxies.MessageText load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return slackmessage.proxies.MessageText.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of MessageTextType
	 * @param messagetexttype
	 */
	public final slackmessage.proxies.Enum_TextType getMessageTextType()
	{
		return getMessageTextType(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageTextType
	 */
	public final slackmessage.proxies.Enum_TextType getMessageTextType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessageTextType.toString());
		if (obj == null)
			return null;

		return slackmessage.proxies.Enum_TextType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessageTextType
	 * @param messagetexttype
	 */
	public final void setMessageTextType(slackmessage.proxies.Enum_TextType messagetexttype)
	{
		setMessageTextType(getContext(), messagetexttype);
	}

	/**
	 * Set value of MessageTextType
	 * @param context
	 * @param messagetexttype
	 */
	public final void setMessageTextType(com.mendix.systemwideinterfaces.core.IContext context, slackmessage.proxies.Enum_TextType messagetexttype)
	{
		if (messagetexttype != null)
			getMendixObject().setValue(context, MemberNames.MessageTextType.toString(), messagetexttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessageTextType.toString(), null);
	}

	/**
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText()
	{
		return getMessageText(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageText.toString());
	}

	/**
	 * Set value of MessageText
	 * @param messagetext
	 */
	public final void setMessageText(java.lang.String messagetext)
	{
		setMessageText(getContext(), messagetext);
	}

	/**
	 * Set value of MessageText
	 * @param context
	 * @param messagetext
	 */
	public final void setMessageText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messagetext)
	{
		getMendixObject().setValue(context, MemberNames.MessageText.toString(), messagetext);
	}

	/**
	 * @return value of MessageText_Block
	 */
	public final slackmessage.proxies.Block getMessageText_Block() throws com.mendix.core.CoreException
	{
		return getMessageText_Block(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageText_Block
	 */
	public final slackmessage.proxies.Block getMessageText_Block(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slackmessage.proxies.Block result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MessageText_Block.toString());
		if (identifier != null)
			result = slackmessage.proxies.Block.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MessageText_Block
	 * @param messagetext_block
	 */
	public final void setMessageText_Block(slackmessage.proxies.Block messagetext_block)
	{
		setMessageText_Block(getContext(), messagetext_block);
	}

	/**
	 * Set value of MessageText_Block
	 * @param context
	 * @param messagetext_block
	 */
	public final void setMessageText_Block(com.mendix.systemwideinterfaces.core.IContext context, slackmessage.proxies.Block messagetext_block)
	{
		if (messagetext_block == null)
			getMendixObject().setValue(context, MemberNames.MessageText_Block.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MessageText_Block.toString(), messagetext_block.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageTextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final slackmessage.proxies.MessageText that = (slackmessage.proxies.MessageText) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SlackMessage.MessageText";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
