// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackmessage.proxies;

public class SlashCommandRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject slashCommandRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SlackMessage.SlashCommandRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Token("Token"),
		TeamID("TeamID"),
		TeamDomain("TeamDomain"),
		EnterpriseID("EnterpriseID"),
		EnterpriseName("EnterpriseName"),
		ChannelID("ChannelID"),
		ChannelName("ChannelName"),
		UserID("UserID"),
		UserName("UserName"),
		Command("Command"),
		Text("Text"),
		ResponseURL("ResponseURL"),
		TriggerID("TriggerID"),
		SslCheck("SslCheck"),
		SlackTimestamp("SlackTimestamp"),
		SlackUserAgent("SlackUserAgent"),
		IsValidRequest("IsValidRequest"),
		UUID("UUID"),
		SlackAppName("SlackAppName"),
		SlashCommandRequest_HttpResponse("SlackMessage.SlashCommandRequest_HttpResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SlashCommandRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SlackMessage.SlashCommandRequest"));
	}

	protected SlashCommandRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject slashCommandRequestMendixObject)
	{
		if (slashCommandRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SlackMessage.SlashCommandRequest", slashCommandRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SlackMessage.SlashCommandRequest");

		this.slashCommandRequestMendixObject = slashCommandRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SlashCommandRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static slackmessage.proxies.SlashCommandRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return slackmessage.proxies.SlashCommandRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static slackmessage.proxies.SlashCommandRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new slackmessage.proxies.SlashCommandRequest(context, mendixObject);
	}

	public static slackmessage.proxies.SlashCommandRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return slackmessage.proxies.SlashCommandRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of TeamID
	 */
	public final java.lang.String getTeamID()
	{
		return getTeamID(getContext());
	}

	/**
	 * @param context
	 * @return value of TeamID
	 */
	public final java.lang.String getTeamID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TeamID.toString());
	}

	/**
	 * Set value of TeamID
	 * @param teamid
	 */
	public final void setTeamID(java.lang.String teamid)
	{
		setTeamID(getContext(), teamid);
	}

	/**
	 * Set value of TeamID
	 * @param context
	 * @param teamid
	 */
	public final void setTeamID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teamid)
	{
		getMendixObject().setValue(context, MemberNames.TeamID.toString(), teamid);
	}

	/**
	 * @return value of TeamDomain
	 */
	public final java.lang.String getTeamDomain()
	{
		return getTeamDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of TeamDomain
	 */
	public final java.lang.String getTeamDomain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TeamDomain.toString());
	}

	/**
	 * Set value of TeamDomain
	 * @param teamdomain
	 */
	public final void setTeamDomain(java.lang.String teamdomain)
	{
		setTeamDomain(getContext(), teamdomain);
	}

	/**
	 * Set value of TeamDomain
	 * @param context
	 * @param teamdomain
	 */
	public final void setTeamDomain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teamdomain)
	{
		getMendixObject().setValue(context, MemberNames.TeamDomain.toString(), teamdomain);
	}

	/**
	 * @return value of EnterpriseID
	 */
	public final java.lang.String getEnterpriseID()
	{
		return getEnterpriseID(getContext());
	}

	/**
	 * @param context
	 * @return value of EnterpriseID
	 */
	public final java.lang.String getEnterpriseID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnterpriseID.toString());
	}

	/**
	 * Set value of EnterpriseID
	 * @param enterpriseid
	 */
	public final void setEnterpriseID(java.lang.String enterpriseid)
	{
		setEnterpriseID(getContext(), enterpriseid);
	}

	/**
	 * Set value of EnterpriseID
	 * @param context
	 * @param enterpriseid
	 */
	public final void setEnterpriseID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enterpriseid)
	{
		getMendixObject().setValue(context, MemberNames.EnterpriseID.toString(), enterpriseid);
	}

	/**
	 * @return value of EnterpriseName
	 */
	public final java.lang.String getEnterpriseName()
	{
		return getEnterpriseName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnterpriseName
	 */
	public final java.lang.String getEnterpriseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnterpriseName.toString());
	}

	/**
	 * Set value of EnterpriseName
	 * @param enterprisename
	 */
	public final void setEnterpriseName(java.lang.String enterprisename)
	{
		setEnterpriseName(getContext(), enterprisename);
	}

	/**
	 * Set value of EnterpriseName
	 * @param context
	 * @param enterprisename
	 */
	public final void setEnterpriseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enterprisename)
	{
		getMendixObject().setValue(context, MemberNames.EnterpriseName.toString(), enterprisename);
	}

	/**
	 * @return value of ChannelID
	 */
	public final java.lang.String getChannelID()
	{
		return getChannelID(getContext());
	}

	/**
	 * @param context
	 * @return value of ChannelID
	 */
	public final java.lang.String getChannelID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChannelID.toString());
	}

	/**
	 * Set value of ChannelID
	 * @param channelid
	 */
	public final void setChannelID(java.lang.String channelid)
	{
		setChannelID(getContext(), channelid);
	}

	/**
	 * Set value of ChannelID
	 * @param context
	 * @param channelid
	 */
	public final void setChannelID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String channelid)
	{
		getMendixObject().setValue(context, MemberNames.ChannelID.toString(), channelid);
	}

	/**
	 * @return value of ChannelName
	 */
	public final java.lang.String getChannelName()
	{
		return getChannelName(getContext());
	}

	/**
	 * @param context
	 * @return value of ChannelName
	 */
	public final java.lang.String getChannelName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChannelName.toString());
	}

	/**
	 * Set value of ChannelName
	 * @param channelname
	 */
	public final void setChannelName(java.lang.String channelname)
	{
		setChannelName(getContext(), channelname);
	}

	/**
	 * Set value of ChannelName
	 * @param context
	 * @param channelname
	 */
	public final void setChannelName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String channelname)
	{
		getMendixObject().setValue(context, MemberNames.ChannelName.toString(), channelname);
	}

	/**
	 * @return value of UserID
	 */
	public final java.lang.String getUserID()
	{
		return getUserID(getContext());
	}

	/**
	 * @param context
	 * @return value of UserID
	 */
	public final java.lang.String getUserID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserID.toString());
	}

	/**
	 * Set value of UserID
	 * @param userid
	 */
	public final void setUserID(java.lang.String userid)
	{
		setUserID(getContext(), userid);
	}

	/**
	 * Set value of UserID
	 * @param context
	 * @param userid
	 */
	public final void setUserID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userid)
	{
		getMendixObject().setValue(context, MemberNames.UserID.toString(), userid);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Command
	 */
	public final java.lang.String getCommand()
	{
		return getCommand(getContext());
	}

	/**
	 * @param context
	 * @return value of Command
	 */
	public final java.lang.String getCommand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Command.toString());
	}

	/**
	 * Set value of Command
	 * @param command
	 */
	public final void setCommand(java.lang.String command)
	{
		setCommand(getContext(), command);
	}

	/**
	 * Set value of Command
	 * @param context
	 * @param command
	 */
	public final void setCommand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String command)
	{
		getMendixObject().setValue(context, MemberNames.Command.toString(), command);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of ResponseURL
	 */
	public final java.lang.String getResponseURL()
	{
		return getResponseURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseURL
	 */
	public final java.lang.String getResponseURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResponseURL.toString());
	}

	/**
	 * Set value of ResponseURL
	 * @param responseurl
	 */
	public final void setResponseURL(java.lang.String responseurl)
	{
		setResponseURL(getContext(), responseurl);
	}

	/**
	 * Set value of ResponseURL
	 * @param context
	 * @param responseurl
	 */
	public final void setResponseURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String responseurl)
	{
		getMendixObject().setValue(context, MemberNames.ResponseURL.toString(), responseurl);
	}

	/**
	 * @return value of TriggerID
	 */
	public final java.lang.String getTriggerID()
	{
		return getTriggerID(getContext());
	}

	/**
	 * @param context
	 * @return value of TriggerID
	 */
	public final java.lang.String getTriggerID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TriggerID.toString());
	}

	/**
	 * Set value of TriggerID
	 * @param triggerid
	 */
	public final void setTriggerID(java.lang.String triggerid)
	{
		setTriggerID(getContext(), triggerid);
	}

	/**
	 * Set value of TriggerID
	 * @param context
	 * @param triggerid
	 */
	public final void setTriggerID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String triggerid)
	{
		getMendixObject().setValue(context, MemberNames.TriggerID.toString(), triggerid);
	}

	/**
	 * @return value of SslCheck
	 */
	public final java.lang.String getSslCheck()
	{
		return getSslCheck(getContext());
	}

	/**
	 * @param context
	 * @return value of SslCheck
	 */
	public final java.lang.String getSslCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SslCheck.toString());
	}

	/**
	 * Set value of SslCheck
	 * @param sslcheck
	 */
	public final void setSslCheck(java.lang.String sslcheck)
	{
		setSslCheck(getContext(), sslcheck);
	}

	/**
	 * Set value of SslCheck
	 * @param context
	 * @param sslcheck
	 */
	public final void setSslCheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sslcheck)
	{
		getMendixObject().setValue(context, MemberNames.SslCheck.toString(), sslcheck);
	}

	/**
	 * @return value of SlackTimestamp
	 */
	public final java.util.Date getSlackTimestamp()
	{
		return getSlackTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of SlackTimestamp
	 */
	public final java.util.Date getSlackTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SlackTimestamp.toString());
	}

	/**
	 * Set value of SlackTimestamp
	 * @param slacktimestamp
	 */
	public final void setSlackTimestamp(java.util.Date slacktimestamp)
	{
		setSlackTimestamp(getContext(), slacktimestamp);
	}

	/**
	 * Set value of SlackTimestamp
	 * @param context
	 * @param slacktimestamp
	 */
	public final void setSlackTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date slacktimestamp)
	{
		getMendixObject().setValue(context, MemberNames.SlackTimestamp.toString(), slacktimestamp);
	}

	/**
	 * @return value of SlackUserAgent
	 */
	public final java.lang.String getSlackUserAgent()
	{
		return getSlackUserAgent(getContext());
	}

	/**
	 * @param context
	 * @return value of SlackUserAgent
	 */
	public final java.lang.String getSlackUserAgent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SlackUserAgent.toString());
	}

	/**
	 * Set value of SlackUserAgent
	 * @param slackuseragent
	 */
	public final void setSlackUserAgent(java.lang.String slackuseragent)
	{
		setSlackUserAgent(getContext(), slackuseragent);
	}

	/**
	 * Set value of SlackUserAgent
	 * @param context
	 * @param slackuseragent
	 */
	public final void setSlackUserAgent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String slackuseragent)
	{
		getMendixObject().setValue(context, MemberNames.SlackUserAgent.toString(), slackuseragent);
	}

	/**
	 * Set value of IsValidRequest
	 * @param isvalidrequest
	 */
	public final slackmessage.proxies.Enum_SlashCommandRequest_ValidRequest getIsValidRequest()
	{
		return getIsValidRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValidRequest
	 */
	public final slackmessage.proxies.Enum_SlashCommandRequest_ValidRequest getIsValidRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.IsValidRequest.toString());
		if (obj == null)
			return null;

		return slackmessage.proxies.Enum_SlashCommandRequest_ValidRequest.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of IsValidRequest
	 * @param isvalidrequest
	 */
	public final void setIsValidRequest(slackmessage.proxies.Enum_SlashCommandRequest_ValidRequest isvalidrequest)
	{
		setIsValidRequest(getContext(), isvalidrequest);
	}

	/**
	 * Set value of IsValidRequest
	 * @param context
	 * @param isvalidrequest
	 */
	public final void setIsValidRequest(com.mendix.systemwideinterfaces.core.IContext context, slackmessage.proxies.Enum_SlashCommandRequest_ValidRequest isvalidrequest)
	{
		if (isvalidrequest != null)
			getMendixObject().setValue(context, MemberNames.IsValidRequest.toString(), isvalidrequest.toString());
		else
			getMendixObject().setValue(context, MemberNames.IsValidRequest.toString(), null);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SlackAppName
	 */
	public final java.lang.String getSlackAppName()
	{
		return getSlackAppName(getContext());
	}

	/**
	 * @param context
	 * @return value of SlackAppName
	 */
	public final java.lang.String getSlackAppName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SlackAppName.toString());
	}

	/**
	 * Set value of SlackAppName
	 * @param slackappname
	 */
	public final void setSlackAppName(java.lang.String slackappname)
	{
		setSlackAppName(getContext(), slackappname);
	}

	/**
	 * Set value of SlackAppName
	 * @param context
	 * @param slackappname
	 */
	public final void setSlackAppName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String slackappname)
	{
		getMendixObject().setValue(context, MemberNames.SlackAppName.toString(), slackappname);
	}

	/**
	 * @return value of SlashCommandRequest_HttpResponse
	 */
	public final system.proxies.HttpResponse getSlashCommandRequest_HttpResponse() throws com.mendix.core.CoreException
	{
		return getSlashCommandRequest_HttpResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of SlashCommandRequest_HttpResponse
	 */
	public final system.proxies.HttpResponse getSlashCommandRequest_HttpResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.HttpResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SlashCommandRequest_HttpResponse.toString());
		if (identifier != null)
			result = system.proxies.HttpResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SlashCommandRequest_HttpResponse
	 * @param slashcommandrequest_httpresponse
	 */
	public final void setSlashCommandRequest_HttpResponse(system.proxies.HttpResponse slashcommandrequest_httpresponse)
	{
		setSlashCommandRequest_HttpResponse(getContext(), slashcommandrequest_httpresponse);
	}

	/**
	 * Set value of SlashCommandRequest_HttpResponse
	 * @param context
	 * @param slashcommandrequest_httpresponse
	 */
	public final void setSlashCommandRequest_HttpResponse(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.HttpResponse slashcommandrequest_httpresponse)
	{
		if (slashcommandrequest_httpresponse == null)
			getMendixObject().setValue(context, MemberNames.SlashCommandRequest_HttpResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SlashCommandRequest_HttpResponse.toString(), slashcommandrequest_httpresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return slashCommandRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final slackmessage.proxies.SlashCommandRequest that = (slackmessage.proxies.SlashCommandRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SlackMessage.SlashCommandRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
